name: Deploy dev to AWS

#turn off deploy to AWS
on:
  pull_request:
    types: [closed]
    branches:
      - dev

jobs:
  aws-deploy:
    runs-on: ubuntu-latest
    env:
      VITE_CLIENT_ID: ${{secrets.VITE_CLIENT_ID}}
      VITE_API_URL: ${{secrets.VITE_API_URL}}
      VITE_CLIENT_URL: ${{secrets.VITE_CLIENT_URL}}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: dev
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: |
          touch .env
          echo VITE_CLIENT_ID="$VITE_CLIENT_ID" >> .env
          echo VITE_API_URL="$VITE_API_URL" >> .env
          echo VITE_CLIENT_URL=flightplan.eaglesoftwareteam.com >> .env
          echo VITE_SITE_URL=flightplan.eaglesoftwareteam.com >> .env

      - run: npm install
      - run: npm run build
      - run: npm run bundle

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: '-rltgoDzvO --delete'
          SOURCE: 'dist/'
          REMOTE_HOST: 'flightplan.eaglesoftwareteam.com'
          REMOTE_USER: ubuntu
          TARGET: '/var/www/html/2025/flight-plan-t7'